databases:
  - name: personal-budget-db
    plan: free
    databaseName: personal_budget

services:
  - type: web
    name: personal-budget
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal-budget-db
          property: connectionString
